# Generated by Django 5.2.7 on 2026-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('revision', 'En Revisión'), ('liberado', 'Liberado')], default='revision', max_length=20),
        ),
    ]
