# Generated by Django 5.2.7 on 2026-02-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0002_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('social_handle', models.CharField(blank=True, help_text='Ej: @JohnPiper', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='main_florife.author'),
        ),
    ]
