# Generated by Django 5.2.7 on 2026-04-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0004_enable_unaccent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraBiblia',
            fields=[
                ('ognt_sort', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libro', models.IntegerField()),
                ('capitulo', models.IntegerField()),
                ('versiculo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Morfologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmac', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_rmac', models.CharField(blank=True, max_length=255, null=True)),
                ('palabra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morfologia', to='main_florife.palabrabiblia')),
            ],
        ),
        migrations.CreateModel(
            name='TraduccionLiteral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espanol', models.CharField(blank=True, max_length=255, null=True)),
                ('palabra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traduccion', to='main_florife.palabrabiblia')),
            ],
        ),
    ]
