# Generated by Django 5.2.7 on 2026-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0005_palabrabiblia_morfologia_traduccionliteral'),
    ]

    operations = [
        migrations.AddField(
            model_name='morfologia',
            name='low_nida_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='traduccionliteral',
            name='griego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
