# Generated by Django 5.2.7 on 2026-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0006_morfologia_low_nida_number_traduccionliteral_griego'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccionliteral',
            name='raiz_griega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
