# Generated by Django 5.2.7 on 2026-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0007_traduccionliteral_raiz_griega'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroBiblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('testamento', models.CharField(default='Nuevo Testamento', max_length=50)),
            ],
        ),
    ]
