# Generated by Django 5.2.7 on 2026-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0008_librobiblia'),
    ]

    operations = [
        migrations.AddField(
            model_name='librobiblia',
            name='estructura_capitulos',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
