# Generated by Django 5.2.7 on 2026-04-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0009_librobiblia_estructura_capitulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='morfologia',
            name='strong',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
