# Generated by Django 5.2.7 on 2026-04-06 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0010_morfologia_strong'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionBiblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersiculoBiblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.IntegerField()),
                ('versiculo', models.IntegerField()),
                ('texto', models.TextField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiculos', to='main_florife.librobiblia')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiculos', to='main_florife.versionbiblia')),
            ],
        ),
    ]
