# Generated by Django 5.2.7 on 2026-04-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0011_versionbiblia_versiculobiblia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiculobiblia',
            name='version',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='versiculobiblia',
            name='libro',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='versiculobiblia',
            unique_together={('version', 'libro', 'capitulo', 'versiculo')},
        ),
        migrations.DeleteModel(
            name='VersionBiblia',
        ),
    ]
