# Generated by Django 5.2.7 on 2026-04-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0012_alter_versiculobiblia_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBibleSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('nbla', 'Nueva Biblia de las Américas'), ('ntv', 'Nueva Traducción Viviente'), ('rvr09', 'Reina Valera 1909')], max_length=20, unique=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'API Bible Sync Statuses',
            },
        ),
    ]
