# Generated by Django 5.2.7 on 2026-05-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0013_apibiblesyncstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('content', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('revision', 'En Revisión'), ('liberado', 'Liberado')], default='revision', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to='main_florife.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='main_florife.category')),
            ],
        ),
    ]
