# Generated by Django 5.2.7 on 2026-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0017_userstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratis'), ('premium', 'Premium'), ('pro', 'Pro')], default='free', max_length=20, verbose_name='Plan'),
        ),
    ]
