# Generated by Django 5.2.7 on 2026-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0018_userprofile_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrongConcord',
            fields=[
                ('topic', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('is_strong', models.BooleanField(default=False)),
                ('is_concord', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Strong/Vine',
                'verbose_name_plural': 'Strong/Vine',
                'db_table': 'strong_concord',
            },
        ),
    ]
