# Generated by Django 5.2.7 on 2026-05-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0019_strongconcord'),
    ]

    operations = [
        migrations.AddField(
            model_name='strongconcord',
            name='strong_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
