# Generated by Django 5.2.7 on 2026-05-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0020_strongconcord_strong_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraHebreo',
            fields=[
                ('oshb_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('libro', models.IntegerField()),
                ('capitulo', models.IntegerField()),
                ('versiculo', models.IntegerField()),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MorfologiaHebreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morph_code', models.CharField(max_length=50)),
                ('strong', models.CharField(blank=True, max_length=20, null=True)),
                ('palabra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morfologia_hebreo', to='main_florife.palabrahebreo')),
            ],
        ),
        migrations.CreateModel(
            name='TraduccionHebreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebreo', models.CharField(max_length=255)),
                ('raiz_hebrea', models.CharField(blank=True, max_length=255, null=True)),
                ('espanol', models.CharField(blank=True, max_length=255, null=True)),
                ('palabra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traduccion_hebreo', to='main_florife.palabrahebreo')),
            ],
        ),
    ]
