# Generated by Django 4.2.11 on 2026-05-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0021_palabrahebreo_morfologiahebreo_traduccionhebreo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StrongConcord',
            new_name='VineConcord',
        ),
        migrations.AlterModelTable(
            name='vineconcord',
            table='vine_concord',
        ),
    ]
