# Generated by Django 4.2.11 on 2026-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0022_rename_strongconcord_vineconcord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrongConcord',
            fields=[
                ('topic', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('definition', models.TextField(blank=True, null=True)),
                ('is_strong', models.BooleanField(default=False)),
                ('is_concord', models.BooleanField(default=False)),
                ('strong_numbers', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Strong',
                'verbose_name_plural': 'Strong',
                'db_table': 'strong_concord',
            },
        ),
        migrations.AlterModelOptions(
            name='vineconcord',
            options={'verbose_name': 'Vine/Concord', 'verbose_name_plural': 'Vine/Concord'},
        ),
    ]
