# Generated by Django 4.2.11 on 2026-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0023_strongconcord_alter_vineconcord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LouwNidaConcord',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('termino_griego', models.TextField(blank=True, null=True)),
                ('definicion_completa', models.TextField(blank=True, null=True)),
                ('glosa_principal', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Louw-Nida',
                'verbose_name_plural': 'Louw-Nida',
                'db_table': 'louw_nida_concord',
            },
        ),
    ]
