# Generated by Django 5.2.7 on 2026-05-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0024_louw_nida_concord'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Descripción para SEO y redes sociales. Máximo 160 caracteres.', null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Descripción para SEO y redes sociales. Máximo 160 caracteres.', null=True),
        ),
    ]
