# Generated by Django 5.2.7 on 2026-06-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0025_article_meta_description_essay_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextos', to='main_florife.librobiblia')),
            ],
            options={
                'verbose_name': 'Contexto de Libro',
                'verbose_name_plural': 'Contextos de Libros',
                'db_table': 'contexto_libro',
            },
        ),
    ]
