# Generated by Django 5.2.7 on 2026-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0026_contextolibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextolibro',
            name='contenido',
            field=models.TextField(),
        ),
    ]
