# Generated by Django 5.2.7 on 2026-06-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0027_alter_contextolibro_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LouwNidaConcord',
        ),
    ]
