# Generated by Django 5.2.7 on 2026-06-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0028_delete_louwnidaconcord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='unicon-users', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de edad',
                'verbose_name_plural': 'Categorías de edad',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MadreMaestraResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(help_text='Contenido completo (soporta HTML)')),
                ('summary', models.TextField(blank=True, help_text='Resumen corto para la tarjeta', null=True)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('revision', 'En Revisión'), ('liberado', 'Liberado')], default='revision', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='main_florife.agecategory')),
            ],
            options={
                'verbose_name': 'Recurso MM',
                'verbose_name_plural': 'Recursos MM',
                'ordering': ['-created_at'],
            },
        ),
    ]
