# Generated by Django 5.2.7 on 2026-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0029_agecategory_madremaestraresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='madremaestraresource',
            name='bible_passage',
            field=models.CharField(blank=True, help_text='Pasaje bíblico (ej. Juan 3:16)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='madremaestraresource',
            name='key_verse',
            field=models.CharField(blank=True, help_text='Versículo clave', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='madremaestraresource',
            name='materials',
            field=models.TextField(blank=True, help_text='Materiales necesarios', null=True),
        ),
        migrations.AddField(
            model_name='madremaestraresource',
            name='objective',
            field=models.TextField(blank=True, help_text='Objetivo de la enseñanza', null=True),
        ),
        migrations.AddField(
            model_name='madremaestraresource',
            name='time_minutes',
            field=models.IntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='madremaestraresource',
            name='content',
            field=models.TextField(blank=True, help_text='Desarrollo completo de la lección (soporta HTML)', null=True),
        ),
    ]
