# Generated by Django 4.2.11 on 2026-06-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_florife', '0031_add_author_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
